# Generated by Django 4.0.4 on 2023-05-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Phonenumber', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher_Info',
        ),
    ]
