# Generated by Django 4.0.4 on 2022-05-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(blank=True, max_length=100)),
                ('Lesson', models.CharField(blank=True, max_length=200)),
                ('Note1', models.CharField(blank=True, max_length=500)),
                ('Note2', models.CharField(blank=True, max_length=500)),
                ('Note3', models.CharField(blank=True, max_length=500)),
                ('Note4', models.CharField(blank=True, max_length=500)),
                ('Note5', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
