# Generated by Django 4.0.4 on 2023-05-12 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
