# Generated by Django 4.0.4 on 2023-05-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0002_delete_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ml', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('dt', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('rf', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('svm', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('linear', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('logistic', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('rein', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('knn', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('dl', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('rnn', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('lstm', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('trans', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('gan', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('cnn', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
            ],
        ),
    ]
